version: '3.8'

services:
  opensearch:
    image: opensearchproject/opensearch:2.10.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - bootstrap.memory_lock=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin  # OpenSearch Admin password
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - opensearch-network

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.10.0
    container_name: opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
    ports:
      - "5601:5601"
    networks:
      - opensearch-network
    depends_on:
      - opensearch

  data-prepper:
    image: opensearchproject/data-prepper:2.10.0
    container_name: data-prepper
    volumes:
      - ./pipeline.yml:/usr/share/data-prepper/pipelines/pipeline.yml  # Arquivo de configuração do pipeline
    ports:
      - "4900:4900"
    networks:
      - opensearch-network
    depends_on:
      - opensearch

volumes:
  opensearch-data:
    driver: local

networks:
  opensearch-network:
    driver: bridge
