pipeline:
  workers: 2
  delay: "100"
  source:
    otel_trace_source:
      ssl: false
      port: 21890
  sink:
    - opensearch:
        hosts: ["http://opensearch:9200"]
        username: "admin"
        password: "admin"
        index: "logs"
