services:
  otel-lgtm:
    image: grafana/otel-lgtm:0.9.1
    container_name: otel-lgtm
    restart: unless-stopped  # Restart container if it fails
    ports:
      - "3000:3000"  # Grafana Port
      - "4317:4317"  # OpenTelemetry (OTLP gRPC) Port
      - "4318:4318"  # OpenTelemetry (OTLP HTTP) Port
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Grafana Admin Password
    # If you want to map local configuration files to the container, uncomment the following lines
    # volumes:
    #   - ./config:/etc/grafana/provisioning  