global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Example of a misconfigured job or field
  - job_name: 'my_custom_job'
    static_configs:
      - targets: ['localhost:9091']
