services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    restart: unless-stopped
    ports:
      - "6831:6831/udp"   # Accepts spans Jaeger Thrift via UDP
      - "6832:6832/udp"   # Accepts spans Jaeger Thrift via UDP (compact format)
      - "5778:5778"       # Configuration endpoint
      - "16686:16686"     # Jaeger UI
      - "14250:14250"     # Accepts data model directly from Agent data model
      - "14268:14268"     # Accepts spans directly from clients
      - "14269:14269"     # Admin Port
      - "9411:9411"       # Accepts spans in Zipkin format
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - jaeger-network

networks:
  jaeger-network:
    driver: bridge