[monitor:///var/lib/docker/containers/*/*-json.log]
index = main
sourcetype = docker:container
disabled = false

[monitor:///var/log/syslog]
index = main
sourcetype = syslog
disabled = false

[monitor:///var/log/auth.log]
index = main
sourcetype = linux_secure
disabled = false
