services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_DEV_SERVER=true
    ports:
      - "8200:8200" # Vault UI
    volumes:
      - vault-data:/vault/data
    cap_add:
      - IPC_LOCK
    restart: unless-stopped

volumes:
  vault-data:
    driver: local