services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0  # Atualizado para 8.7.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_PASSWORD=changeme
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:8.7.0  # Já estava atualizado para 8.7.0
    ports:
      - "5044:5044"  # Beats
      - "9600:9600"  # API de monitoramento
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.0  # Atualizado para 8.7.0
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - elk
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"

volumes:
  esdata:
    driver: local

networks:
  elk:
    driver: bridge
