# ============================================================
#  Utils
# ============================================================
.PHONY: ps logs health urls nuke

ps:
	@docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"

logs:
	@if [ -z "$(STACK)" ]; then echo "$(RED)Usage: make logs STACK=<path>  e.g. STACK=observability/elk$(RESET)"; exit 1; fi
	docker compose -f $(STACK)/docker-compose.yml logs -f --tail=100

health:
	@echo "$(CYAN)── Container health status ─────────────────────────────$(RESET)"
	@docker ps --format "table {{.Names}}\t{{.Status}}" | grep -v "^NAMES"

urls:
	@echo ""
	@echo "$(CYAN)╔══════════════════════════════════════════════════════════╗$(RESET)"
	@echo "$(CYAN)║                   Service URLs                          ║$(RESET)"
	@echo "$(CYAN)╚══════════════════════════════════════════════════════════╝$(RESET)"
	@echo "$(GREEN)Prometheus Stack$(RESET)"
	@echo "  Grafana          http://localhost:3000      admin/admin"
	@echo "  Prometheus       http://localhost:9090"
	@echo "  Alertmanager     http://localhost:9093"
	@echo "  cAdvisor         http://localhost:8080"
	@echo "  Loki             http://localhost:3100"
	@echo ""
	@echo "$(GREEN)LGTM$(RESET)"
	@echo "  Grafana (LGTM)   http://localhost:3001      admin/admin"
	@echo "  Tempo            http://localhost:3200"
	@echo "  Tempo OTLP gRPC  localhost:4319"
	@echo "  Tempo OTLP HTTP  localhost:4320"
	@echo "  Mimir            http://localhost:9009"
	@echo "  Loki (LGTM)      http://localhost:3101"
	@echo ""
	@echo "$(GREEN)ELK$(RESET)"
	@echo "  Kibana           http://localhost:5601"
	@echo "  Elasticsearch    http://localhost:9200"
	@echo "  Logstash TCP     localhost:5000"
	@echo ""
	@echo "$(GREEN)Splunk$(RESET)"
	@echo "  Splunk Web       http://localhost:8000      admin/changeme123!"
	@echo "  HEC              http://localhost:8088/services/collector"
	@echo ""
	@echo "$(GREEN)OTel$(RESET)"
	@echo "  Jaeger           http://localhost:16686"
	@echo "  Zipkin           http://localhost:9411"
	@echo "  OTel GRPC        localhost:4317"
	@echo "  OTel HTTP        localhost:4318"
	@echo "  zPages           http://localhost:55679/debug/tracez"
	@echo ""
	@echo "$(GREEN)Databases$(RESET)"
	@echo "  pgAdmin          http://localhost:5050      admin@admin.com/admin"
	@echo "  PostgreSQL       localhost:5432             admin/admin"
	@echo "  phpMyAdmin       http://localhost:5051      admin/admin  (MySQL)"
	@echo "  MySQL            localhost:3306             admin/admin"
	@echo "  phpMyAdmin       http://localhost:5052      admin/admin  (MariaDB)"
	@echo "  MariaDB          localhost:3307             admin/admin"
	@echo "  RedisInsight     http://localhost:5540"
	@echo "  Redis            localhost:6379             password: admin"
	@echo "  Mongo Express    http://localhost:8082      admin/admin"
	@echo "  MongoDB          localhost:27017            admin/admin"
	@echo "  Cassandra CQL    localhost:9042             (use cqlsh)"
	@echo "  MinIO Console    http://localhost:9001      admin/admin123"
	@echo "  MinIO S3 API     http://localhost:9000      admin/admin123"
	@echo "  Elasticsearch    http://localhost:9201"
	@echo "  Dejavu UI        http://localhost:1358"
	@echo "  Meilisearch      http://localhost:7700      masterkey"
	@echo ""
	@echo "$(GREEN)Messaging$(RESET)"
	@echo "  Kafka UI         http://localhost:8081"
	@echo "  Kafka            localhost:9092"
	@echo "  RabbitMQ UI      http://localhost:15672     admin/admin"
	@echo "  RabbitMQ AMQP    localhost:5672"
	@echo "  NATS             localhost:4222"
	@echo "  NATS Monitoring  http://localhost:8222"
	@echo ""
	@echo "$(GREEN)Infra$(RESET)"
	@echo "  Traefik          http://localhost:8083"
	@echo "  Consul           http://localhost:8500"
	@echo "  Vault            http://localhost:8200      token: root"
	@echo "  Kong (proxy)     http://localhost:8000"
	@echo "  Kong (admin)     http://localhost:8001"
	@echo "  Konga            http://localhost:1337"
	@echo "  Keycloak         http://localhost:8180      admin/admin"
	@echo "  Portainer        http://localhost:9010"
	@echo "  NGINX            http://localhost:8091"
	@echo "  Uptime Kuma      http://localhost:3002"
	@echo "  Unleash          http://localhost:4242      admin/unleash4all"
	@echo ""
	@echo "$(GREEN)Security$(RESET)"
	@echo "  OWASP ZAP        http://localhost:8093      apikey: zapkey"
	@echo "  ZAP API UI       http://localhost:8093/UI"
	@echo ""
	@echo "$(GREEN)Web$(RESET)"
	@echo "  LAMP Apache/PHP  http://localhost:8090"
	@echo "  LAMP phpMyAdmin  http://localhost:5053      admin/admin"
	@echo "  LAMP MySQL       localhost:3308             admin/admin"
	@echo "  LEMP NGINX/PHP   http://localhost:8092"
	@echo "  LEMP phpMyAdmin  http://localhost:5054      admin/admin"
	@echo "  LEMP MySQL       localhost:3309             admin/admin"
	@echo "  Mailpit UI       http://localhost:8025"
	@echo "  Mailpit SMTP     localhost:1025"
	@echo "  Hugo             http://localhost:1313      (live reload)"
	@echo ""

nuke:
	@echo "$(RED)⚠ This will remove ALL containers, volumes and networks!$(RESET)"
	@read -p "Are you sure? [y/N] " confirm && [ "$$confirm" = "y" ] || exit 1
	@$(MAKE) down-all
	docker volume prune -f
	docker network prune -f
	@echo "$(GREEN)✔ Done.$(RESET)"
